version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: db
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: auth-service
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: 1111
      KEYCLOAK_HOSTNAME: localhost
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: start-dev --hostname localhost

  db:
    image: postgres:latest
    container_name: auth-service-db
    environment:
      POSTGRES_DB: auth-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
