spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth-service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1111

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true