spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/auth-service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1111

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: authapp
            client-secret: Q1jWxCRIAVFwjdUnSlLy8n81IkjDaqmg
            scope: openid
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/springboot
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/springboot
          jwt-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

springdoc:
  default-produces-media-type: application/json
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  info:
    title: Authorization Service
    description: This is the API documentation for Auth-Service.
    version: v1.0.0

server:
  servlet:
    context-path: /api/v1/
  port: 8081


